# Generated by Django 4.0.4 on 2022-04-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.TimeField()),
                ('priority', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Create_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=255)),
                ('evaliator', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True, default='')),
                ('note', models.DecimalField(decimal_places=1, max_digits=2)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tables.tasks')),
            ],
        ),
    ]
