# Generated by Django 4.0.4 on 2022-04-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='name_task',
            new_name='description_task',
        ),
    ]
