# Generated by Django 4.0.4 on 2022-04-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_rename_name_task_groups_description_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['id']},
        ),
    ]
